### ISSUE TITLE
test

### ISSUE THREAD

**Issue by HITYAOTIAN** [zz10001/LITS2017-main1#1]
请问能否上传test.py代码，希望学习一下

**Comment by zz10001** [comment]
emm，我感觉我test写的有点问题（太烂了）就没发出来，预测70个样例差不多得4小时，如果不熟悉的话可以先做成标签和图像一一对应的，就是在同一个切片维度。我那个预处理是取连续3张切片作为输入，最中间作为标签0.0

**Comment by HITYAOTIAN** [comment]
我还是个新手，想学习一下您的test代码，可否将您的代码私发至我的邮箱？1398837199@qq.com，万分感谢！

**Comment by HITYAOTIAN** [comment]
您好，我是一名初学者，最近刚刚接触这个领域，感觉您的代码写的很清晰，对新手挺友好的，但是没有test.py代码就很难受，希望您能上传一份test.py的代码，不胜感激！

**Comment by zz10001** [comment]
最近不太方便，你可以先尝试一下只做单张切片作为输入，可能好些一点。将来可能coming soon

**Comment by zz10001** [comment]
> 您好，我是一名初学者，最近刚刚接触这个领域，感觉您的代码写的很清晰，对新手挺友好的，但是没有test.py代码就很难受，希望您能上传一份test.py的代码，不胜感激！

Hello, 如果没有什么问题的话我将关闭这个issue，你也可以自己先写test.py，我可以帮你看看。另外，最近也有肿瘤分割相关的代码开源了，你也可以先看看[DoDNet](https://github.com/jianpengz/DoDNet)

**Comment by zz10001** [comment]
hello, 我已经提交了test代码，希望对你有帮助。

**Comment by HITYAOTIAN** [comment]
谢谢！
