### ISSUE TITLE
When I run train.py, an error occurs。‘AttributeError: 'Namespace' object has no attribute 'deepsupervision'’ Do you know the reason?

### ISSUE THREAD

**Issue by xianfengj** [zz10001/LITS2017-main1#12]
When I run train.py, an error occurs。‘AttributeError: 'Namespace' object has no attribute 'deepsupervision'’
Do you know the reason?

**Comment by zz10001** [comment]
Hello, you just need add deepsupervision on here
![image](https://user-images.githubusercontent.com/39954774/221417624-392a4d3e-bb5a-422f-88d7-8a63a2c0fe3a.png)

**Comment by xianfengj** [comment]
> 您好，您只需要在此处添加深度监督 ![图像](https://user-images.githubusercontent.com/39954774/221417624-392a4d3e-bb5a-422f-88d7-8a63a2c0fe3a.png)

谢谢啊   不好意思请教一下我刚开始学， 能稍微详细一点吗，在这里怎么添加deepsupervision啊

**Comment by xianfengj** [comment]
搞定了  谢谢

**Comment by yyqxadwq** [comment]
您好,可以请教一下怎么添加的deepsupervision吗

**Comment by FanyDu** [comment]
> 搞定了 谢谢

您好！怎么修改的，麻烦能不能发一下，谢谢

**Comment by FanyDu** [comment]
> 搞定了 谢谢

@xianfengj 

您好！请教一下怎么修改，能不能发一下，谢谢！

**Comment by FanyDu** [comment]
> 搞定了 谢谢

请问是怎么搞定了，能不能分享一下呢，谢谢
