### ISSUE TITLE
the file"nii2png.py" doesn't work

### ISSUE THREAD

**Issue by xianfengj** [zz10001/LITS2017-main1#14]
the file"nii2png.py" doesn't work,

**Comment by zz10001** [comment]
> the file"nii2png.py" doesn't work,

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E5%9C%A8%E6%8F%90%E9%97%AE%E4%B9%8B%E5%89%8D
