### ISSUE TITLE
关于分割标签的问题

### ISSUE THREAD

**Issue by xiaoc-lee** [zz10001/LITS2017-main1#2]
你好，请问该项目是按照肝脏和肿瘤两个标签进行分割的吗，例如下面写在dataset里的代码，谢谢
        liver_label = npmask.copy()
        liver_label[npmask == 2] = 1
        liver_label[npmask == 1] = 1

        tumor_label = npmask.copy()
        tumor_label[npmask == 1] = 0
        tumor_label[npmask == 2] = 1

        nplabel = np.empty((448,448,2))
        nplabel[:, :, 0] = liver_label
        nplabel[:, :, 1] = tumor_label
        nplabel = nplabel.transpose((2, 0, 1))

**Comment by zz10001** [comment]
是的
