### ISSUE TITLE
运行出现错误

### ISSUE THREAD

**Issue by lcl180** [zz10001/LITS2017-main1#3]
您好，在你这个项目下面看到你正在进行3D肝脏肿瘤分割项目，我在你运行分享的3DUNet-Pytorch-master的时候，出现了下面的错误：RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 3，这个错误的意思是图片和标签的大小不吻合，这是为什么呢？期待您的额回复，谢谢！

**Comment by lcl180** [comment]
ResUNet网络的输出大小是输入的两倍，于是我猜测preprocess_LITS.py中的# 降采样，（对x和y轴进行降采样，slice轴的spacing归一化到slice_down_scale）
        ct_array = ndimage.zoom(ct_array, (ct.GetSpacing()[-1] / self.slice_down_scale, self.xy_down_scale, self.xy_down_scale), order=3)
        # seg_array = ndimage.zoom(seg_array, (ct.GetSpacing()[-1] / self.slice_down_scale, self.xy_down_scale, self.xy_down_scale), order=0)
这个部分出现错误，ct_array应该降采样，而seg_array 不应该降采样，所以我修改了seg_array = ndimage.zoom(seg_array, (ct.GetSpacing()[-1] / self.slice_down_scale, 1, 1), order=0)
但是，结果显示：RuntimeError: stack expects each tensor to be equal size, but got [48, 512, 512] at entry 0 and [48, 256, 256] at entry 1
还是出现图片和标签大小不一致的问题，请问这是哪里出现问题了呢？

**Comment by zz10001** [comment]
建议看下[这个](https://github.com/assassint2017/MICCAI-LITS2017/blob/master/data_prepare/get_training_set.py)数据预处理，ResUNet就是适配这个预处理的，然后可以在ResUnet的各个阶段把它的output大小打印出来，看看那个对不上，不过从报错来看，应该[这里](https://github.com/lee-zq/3DUNet-Pytorch/blob/a7ca7458d5bb4fc1d5f38d940edbcbe2bbda108b/models/ResUNet.py#L187)就报错了。可以在后面print一下output的维度

**Comment by lcl180** [comment]
> 建议看下[这个](https://github.com/assassint2017/MICCAI-LITS2017/blob/master/data_prepare/get_training_set.py)数据预处理，ResUNet就是适配这个预处理的，然后可以在ResUnet的各个阶段把它的output大小打印出来，看看那个对不上，不过从报错来看，应该[这里](https://github.com/lee-zq/3DUNet-Pytorch/blob/a7ca7458d5bb4fc1d5f38d940edbcbe2bbda108b/models/ResUNet.py#L187)就报错了。可以在后面print一下output的维度

我运行preprocess_LITS.py对CT图像进行预处理后，再运行dataset_lits_val.py时，显示标签和图像大小都是256*256，而且只有44个CT图像，剩余的为什么不能打印出来图像和标签的size?

**Comment by zz10001** [comment]
> 我运行preprocess_LITS.py对CT图像进行预处理后，再运行dataset_lits_val.py时，显示标签和图像大小都是256*256，而且只有44个CT图像，剩余的为什么不能打印出来图像和标签的size?

它的运行步骤是:
1.`python ./preprocess_LiTS.py`
2. `change the some parameters in config.py,especially, please set --dataset_path to ./fixed_data`
3. `python train.py --save model_name`
4. `test.py`
你为什么会运行process后在运行dataset_lits_val.py呢，运行train的时候在**ResUNet**中打印出各个output的shape对比一下和target的shape，找到问题再改相应的代码。如果对这方面还有点问题的话，建议先跑一次[MICCAI-LITS2017](https://github.com/assassint2017/MICCAI-LITS2017)理一下整体的思路。

PS：我没有跑过那个项目（3D UNet）

**Comment by lcl180** [comment]
> > 我运行preprocess_LITS.py对CT图像进行预处理后，再运行dataset_lits_val.py时，显示标签和图像大小都是256*256，而且只有44个CT图像，剩余的为什么不能打印出来图像和标签的size?
> 
> 它的运行步骤是:
> 1.`python ./preprocess_LiTS.py`
> 2. `change the some parameters in config.py,especially, please set --dataset_path to ./fixed_data`
> 3. `python train.py --save model_name`
> 4. `test.py`
> 你为什么会运行process后在运行dataset_lits_val.py呢，运行train的时候在**ResUNet**中打印出各个output的shape对比一下和target的shape，找到问题再改相应的代码。如果对这方面还有点问题的话，建议先跑一次[MICCAI-LITS2017](https://github.com/assassint2017/MICCAI-LITS2017)理一下整体的思路。
> 
> PS：我没有跑过那个项目（3D UNet）
好的，谢谢帮助
