### ISSUE TITLE
网络总是报错tensor不匹配

### ISSUE THREAD

**Issue by pangda72** [zz10001/LITS2017-main1#6]
你好，前辈可以请教一些问题吗 ，我参考您的代码，2D 的网络，但是总是报错通道不匹配，我不知道是什么原因，还有就是我是nill格式数据集，需要转换为png格式输入吗

**Comment by zz10001** [comment]
你好，请问下你是参考了那部分代码呢，用的什么数据集进行训练的，数据预处理怎么样，报的错具体是什么呢
