### ISSUE TITLE
关于如何生成肝脏预测结果

### ISSUE THREAD

**Issue by corahuahua** [zz10001/LITS2017-main1#8]
请问您在百度云盘提供的肝脏ROI是如何取得的
方便提供生成肝脏ROI的代码吗？感谢您

**Comment by zz10001** [comment]
> 请问您在百度云盘提供的肝脏ROI是如何取得的
> 方便提供生成肝脏ROI的代码吗？感谢您

可以重新跑一下代码跑出肝脏的结果，或者直接拿[这里](https://github.com/xmengli999/H-DenseUNet)的用，后续在一个区域内分割肝脏肿瘤
